#hey travis we need super user level permissions in order to execute this build
sudo: required
#hey travis we need to download docker to have a copy of it
services:
  - docker

  #executed before our tests run
before_install:
#build docker image
  - docker build -t elijoos/docker-react -f Dockerfile.dev .
  #^returns the Image ID^ therefore we tag it with -t elijoos/repo_name
  #   we could use "testme" or "imageName" for tag but might as well organize

#contain all commands need to be ran to execute tests. If each test != 0, then failed
script:
  - docker run -e CI=true elijoos/docker-react npm run test

#lesson 96. All about deploying--Tell travis CI -> AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-243086078473"
  bucket_path: "docker-react"
  #only deploy app once master branch gets new code
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"